[project]
name = "youtube-video-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytube>=15.0.0",
    "requests>=2.32.3",
    "streamlit>=1.44.1",
    "yt-dlp>=2025.3.31",
]
